### PR TITLE
update archaic and sexist example

### PR DESCRIPTION
**Pull request by erintherad**
Let's update this to an example that all people can understand and relate to

### CODE REVIEW

**Comment by jkoppe** [comment]
This change is a good idea. Thanks for submitting the PR.

**Comment by iangfleming** [comment]
Yes please! 👍

**Comment by caseymhunt** [comment]
Yeah this is gross, please accept the PR.

**Comment by Poppadopolous** [comment]
Great change !  Please implement this.

**Comment by clebauer** [comment]
Same, please implement this. g r o s s.

**Comment by mdschwarz** [comment]
+1.  Wow.

**Comment by smpdarnell** [comment]
+1. Please accept.

**Pull request merged**
