### PR TITLE
Remove broken URL in Linux+IPv6-HOWTO.xml

### PR DESCRIPTION
**Pull request by pbiering**
Remove broken URL in Linux+IPv6-HOWTO.xml

### CODE REVIEW

**Comment by ser** [comment]
i am not precisely sure what does it mean that your "minor test" failed to build - i will investigate it shortly

**Comment by ser** [comment]
@martin-a-brown - it seems we have a problem with builder. https://semaphoreci.com/random/ldp/branches/master/builds/538 --> "Linux+IPv6-HOWTO.html" file was not rendered at all. "Linux+IPv6-HOWTO.pdf" is OK, "Linux+IPv6-HOWTO-single.html" is OK, "Linux+IPv6-HOWTO.txt" is OK - but "index.html -> Linux+IPv6-HOWTO.html" is not being rendered.

**Comment by pbiering** [comment]
@ser : "your "minor test" failed to build"
Probably a leftover before rebase, but in the end my PR only contained one diff.

**Comment by ser** [comment]
No, there are definitely issues on our side which we must fix, @martin-a-brown probably is more familiar with that part so I would wait for his feedback

**Comment by martin-a-brown** [comment]
Hi there @ser,

I wonder if it's the `--size-only` option to rsync, as I cannot replicate this.

  `rsync --stats --size-only -rvlz  --delete-before  ...`

Do you have access to the $SEMAPHORE_CACHE_DIR (and/or do I have access to that location?)  to compare that data to the data that got synchronized to the ibiblio location?

-Martin

**Comment by ser** [comment]
I'm stupid - more information soon :)

**Comment by ser** [comment]
OK, everything is ready and working properly, I am creating a mini-doc to explain :)

**Pull request merged**
