### PR TITLE
Grammar/spelling fixes for Bash Prog Intro

### PR DESCRIPTION
**Pull request by highb**
This commit contains some minor grammatical/spelling fixes
for the Bash Programming Into HOWTO.

My editor also cleaned up some EOL spaces, if that is annoying I can reconfigure it to stop doing that.

### CODE REVIEW

**Comment by martin-a-brown** [comment]
Good morning Brandon,

I started reviewing the diff of the pull request and noticed that most of the corrections were whitespace diff.  I have no objection at all to the whitespace diff.  In the future, could you split the whitespace diff from the corrections?

Next, I just wanted to throw my eye over the updates and I found two little errors in your patch.

1) You have created a sentence that says "Any feedback will is appreciated, especially ..."  I think you want to drop the "will".

2) I think dilemma is correctly written dillema.

Perhaps you could make those two corrections and then resubmit?

If you want to split the whitespace diff this time, feel free, but please don't worry about it.  It's not a big deal.

Oh, and hello from another fellow in PDX,

-Martin

**Comment by martin-a-brown** [comment]
Good morning again Brandon,

I'll be merging your request now.  I will make the corrections that I mentioned above.

-Martin

**Comment by highb** [comment]
@martin-a-brown Arg, sorry I didn't see this update on the PR. Thanks for handling those updates for me!

**Comment by martin-a-brown** [comment]
Hi there Brandon,

>@martin-a-brown Arg, sorry I didn't see this update on the PR. Thanks for handling those updates for me!

No sweat!  No worries!  They were good updates!

Best regards,

-Martin

-- 
Martin A. Brown
http://linux-ip.net/

**Pull request merged**
