### PR TITLE
Adv routing howto rpfilter

### PR DESCRIPTION
**Pull request by pbiering**
superseeds https://github.com/tLDP/LDP/pull/105

### CODE REVIEW

**Comment by pbiering** [comment]
verified conversion with
```
openjade -t sgml -i html -V nochunks -d "../../../builder/dsssl/ldp.dsl#html"  Adv-Routing-HOWTO.sgml >Adv-Routing-HOWTO.html
```

**Review by pbiering — COMMENTED** [review]
self-reviewed

**Review by martin-a-brown — APPROVED** [review]
:+1: It's good Docbook SGML 4.  And, the additional detail on `rp_filter` is good.

I've confirmed that the `ldptool` (in a development environment) can process the tool for all of the usual outputs and that that the EPS file gets embedded correctly into the HTML and PDF outputs.

Thank you, Peter for assisting Leroy in completing this submission.

**Comment by pbiering** [comment]
> It's good Docbook SGML 4. And, the additional detail on `rp_filter` is good.
> 
> I've confirmed that the `ldptool` (in a development environment) can process the tool for all of the usual outputs and that that the EPS file gets embedded correctly into the HTML and PDF outputs.

Thank you for review!

**Pull request merged**
